### ISSUE TITLE
create overview map

### ISSUE THREAD

**Issue by isgiddy** [polar-gliders-operations/web-portal#2]
- [x]  72 hour wind forecast
- [x] latest ice map (static)
- [ ]  platform locations

**Comment by isgiddy** [comment]
@marcelduplessis worked on this. 
Will work to integrate platform locations to the existing maps once the platforms have been deployed

**Comment by isgiddy** [comment]
Issue with proportions on the website - need to figure this out still

**Comment by jmedholm** [comment]
- [ ] Remove the track and add images of the SGs and the SB to the overview plot
