### ISSUE TITLE
sailbuoy plot

### ISSUE THREAD

**Issue by isgiddy** [polar-gliders-operations/web-portal#4]

**Comment by isgiddy** [comment]
@jmedholm has worked on this. Thanks! Will test and integrate.

**Comment by isgiddy** [comment]
`/Users/thedon/Dropbox/Work/SailBuoy Internship/Webplots/Test/chromedriver`

this needs to be somewhere locally on the polar gliders server...@jmedholm can you add this to your local directory on the server?

**Comment by jmedholm** [comment]
Added this to /home/johan on the server.

**Comment by isgiddy** [comment]
there is an OS error, can you make sure the chromedriver is for linux?

**Comment by jmedholm** [comment]
Downloaded the latest Linux version, and replaced it.
